### ISSUE TITLE
BufferOverflowException

### ISSUE THREAD

**Issue by xiecai1234** [ChenLittlePing/LearningVideo#28]
2024-04-03 16:09:32.049 11510-11563 AndroidRuntime          com.cxp.learningvideo                E  FATAL EXCEPTION: pool-2-thread-2
                                                                                                    Process: com.cxp.learningvideo, PID: 11510
                                                                                                    java.nio.BufferOverflowException
                                                                                                    	at java.nio.ByteBuffer.put(ByteBuffer.java:656)
                                                                                                    	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:272)
                                                                                                    	at com.cxp.learningvideo.media.encoder.BaseEncoder.encode(BaseEncoder.kt:123)
                                                                                                    	at com.cxp.learningvideo.media.encoder.BaseEncoder.loopEncode(BaseEncoder.kt:99)
                                                                                                    	at com.cxp.learningvideo.media.encoder.BaseEncoder.run(BaseEncoder.kt:76)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by ChenLittlePing** [comment]
您的来信我已收到，谢谢！

**Comment by LianJ333** [comment]
这是来自连泽全QQ邮箱的自动回复邮件。您好，您的邮件我已经收到。连泽全
